# Generated by Django 3.1 on 2020-08-15 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_forgotpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forgotpassword',
            old_name='token',
            new_name='activation_key',
        ),
    ]
