# Generated by Django 3.1 on 2020-08-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20200815_0639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForgotPassword',
        ),
    ]
