# Generated by Django 3.1 on 2020-08-15 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_forgotpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotpassword',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='forgotpassword',
            name='updated_at',
        ),
    ]
