# Generated by Django 3.1 on 2020-08-15 08:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_auto_20200815_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpassword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forgotpassword',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='activation_key',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
