# Generated by Django 3.0.8 on 2020-08-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_auto_20200816_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotpassword',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='forgotpassword',
            name='exipred_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
